Disable the test directory.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3608,7 +3608,7 @@ fi
 
 done
 
-ac_config_files="$ac_config_files Makefile src/Makefile src/BitSet/Makefile src/Integer/Makefile doc/Makefile doc/user.doxyconf-pdf doc/devref.doxyconf-pdf doc/user.doxyconf-html doc/devref.doxyconf-html test/Makefile ppl.lsm ppl.spec"
+ac_config_files="$ac_config_files Makefile src/Makefile src/BitSet/Makefile src/Integer/Makefile doc/Makefile doc/user.doxyconf-pdf doc/devref.doxyconf-pdf doc/user.doxyconf-html doc/devref.doxyconf-html ppl.lsm ppl.spec"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -3948,12 +3948,11 @@ do
   "doc/devref.doxyconf-pdf" ) CONFIG_FILES="$CONFIG_FILES doc/devref.doxyconf-pdf" ;;
   "doc/user.doxyconf-html" ) CONFIG_FILES="$CONFIG_FILES doc/user.doxyconf-html" ;;
   "doc/devref.doxyconf-html" ) CONFIG_FILES="$CONFIG_FILES doc/devref.doxyconf-html" ;;
-  "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "ppl.lsm" ) CONFIG_FILES="$CONFIG_FILES ppl.lsm" ;;
   "ppl.spec" ) CONFIG_FILES="$CONFIG_FILES ppl.spec" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:3956: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:3955: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -4169,7 +4168,7 @@ for as_mkdir_dir in `IFS='/\\'; set X $as_dummy; shift; echo "$@"`; do
       as_incr_dir=$as_incr_dir/$as_mkdir_dir
       test -d "$as_incr_dir" ||
         mkdir "$as_incr_dir" ||
-	{ { echo "$as_me:4172: error: cannot create \"$ac_dir\"" >&5
+	{ { echo "$as_me:4171: error: cannot create \"$ac_dir\"" >&5
 echo "$as_me: error: cannot create \"$ac_dir\"" >&2;}
    { (exit 1); exit 1; }; }
     ;;
@@ -4206,7 +4205,7 @@ esac
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:4209: creating $ac_file" >&5
+    { echo "$as_me:4208: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -4224,7 +4223,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4227: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4226: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4237,7 +4236,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4240: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4239: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4298,7 +4297,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:4301: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:4300: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -4309,7 +4308,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:4312: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:4311: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -4322,7 +4321,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:4325: error: cannot find input file: $f" >&5
+           { { echo "$as_me:4324: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -4439,7 +4438,7 @@ cat >>$CONFIG_STATUS <<\_ACEOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:4442: $ac_file is unchanged" >&5
+      { echo "$as_me:4441: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -4466,7 +4465,7 @@ for as_mkdir_dir in `IFS='/\\'; set X $as_dummy; shift; echo "$@"`; do
       as_incr_dir=$as_incr_dir/$as_mkdir_dir
       test -d "$as_incr_dir" ||
         mkdir "$as_incr_dir" ||
-	{ { echo "$as_me:4469: error: cannot create \"$ac_dir\"" >&5
+	{ { echo "$as_me:4468: error: cannot create \"$ac_dir\"" >&5
 echo "$as_me: error: cannot create \"$ac_dir\"" >&2;}
    { (exit 1); exit 1; }; }
     ;;
@@ -4531,7 +4530,7 @@ case $srcdir in
     ac_top_srcdir=$ac_top_builddir$srcdir ;;
 esac
 
-  { echo "$as_me:4534: executing $ac_dest commands" >&5
+  { echo "$as_me:4533: executing $ac_dest commands" >&5
 echo "$as_me: executing $ac_dest commands" >&6;}
   case $ac_dest in
     default-1 )
@@ -4647,7 +4646,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_dir || continue
 
-    { echo "$as_me:4650: configuring in $ac_dir" >&5
+    { echo "$as_me:4649: configuring in $ac_dir" >&5
 echo "$as_me: configuring in $ac_dir" >&6;}
     { case "$ac_dir" in
   [\\/]* | ?:[\\/]* ) as_incr_dir=;;
@@ -4662,7 +4661,7 @@ for as_mkdir_dir in `IFS='/\\'; set X $as_dummy; shift; echo "$@"`; do
       as_incr_dir=$as_incr_dir/$as_mkdir_dir
       test -d "$as_incr_dir" ||
         mkdir "$as_incr_dir" ||
-	{ { echo "$as_me:4665: error: cannot create \"$ac_dir\"" >&5
+	{ { echo "$as_me:4664: error: cannot create \"$ac_dir\"" >&5
 echo "$as_me: error: cannot create \"$ac_dir\"" >&2;}
    { (exit 1); exit 1; }; }
     ;;
@@ -4703,7 +4702,7 @@ esac
     elif test -f $ac_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:4706: WARNING: no configuration information is in $ac_dir" >&5
+      { echo "$as_me:4705: WARNING: no configuration information is in $ac_dir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2;}
       ac_sub_configure=
     fi
@@ -4717,12 +4716,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2;}
         ac_sub_cache_file=$ac_top_builddir$cache_file ;;
       esac
 
-      { echo "$as_me:4720: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_srcdir" >&5
+      { echo "$as_me:4719: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_srcdir ||
-        { { echo "$as_me:4725: error: $ac_sub_configure failed for $ac_dir" >&5
+        { { echo "$as_me:4724: error: $ac_sub_configure failed for $ac_dir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_dir" >&2;}
    { (exit 1); exit 1; }; }
     fi
